#!/usr/bin/env python
import click
import boto.ec2
import boto3
from prettytable import PrettyTable

@click.command()
def main():

    ec2_conn = boto.ec2.connect_to_region('us-east-1')
    spot_request = ec2_conn.get_all_spot_instance_requests()

    client = boto3.client('ec2')
    table = PrettyTable(['User', 'Instance Type', 'Internal IP', 'External IP'])

    for r in spot_request:

        state = r.state
        if state == 'active':
 
            instance_id = r.instance_id
            response = client.describe_instances(InstanceIds=[instance_id])
        
            internal_ip = response['Reservations'][0]['Instances'][0]['PrivateIpAddress']
            external_ip = response['Reservations'][0]['Instances'][0]['PublicIpAddress']

            instance_type = ec2_conn.get_instance_attribute(instance_id, 'instanceType')['instanceType']
            user = r.tags['User']
        
            table.add_row([user, instance_type, internal_ip, external_ip])
    print table


if __name__ == "__main__":
    main()
